import type { languages } from 'monaco-editor'

/** Monarch tokenizer for Pine Script v5 — enough for MVP highlighting. */
export const pineLanguage: languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.pine',
  keywords: [
    'indicator',
    'strategy',
    'library',
    'if',
    'else',
    'for',
    'while',
    'switch',
    'var',
    'varip',
    'import',
    'export',
    'and',
    'or',
    'not',
    'true',
    'false',
    'na',
    'float',
    'int',
    'bool',
    'string',
    'color',
    'line',
    'label',
    'box',
    'table',
    'array',
    'matrix',
    'map',
    'series',
    'simple',
    'const',
    'input',
    'plot',
    'plotshape',
    'plotchar',
    'plotcandle',
    'plotbar',
    'hline',
    'fill',
    'bgcolor',
    'barcolor',
    'alertcondition',
    'alert',
    'to',
    'by',
    'break',
    'continue',
    'return',
  ],
  namespaces: [
    'ta',
    'math',
    'request',
    'strategy',
    'input',
    'syminfo',
    'timeframe',
    'ticker',
    'chart',
    'barstate',
    'session',
    'dayofweek',
    'color',
    'shape',
    'location',
    'size',
    'plot',
    'display',
    'format',
    'scale',
    'adjustment',
    'currency',
    'alert',
    'order',
    'text',
    'position',
    'extend',
    'xloc',
    'yloc',
    'line',
    'label',
    'box',
    'table',
    'array',
    'matrix',
    'map',
    'str',
    'runtime',
    'log',
  ],
  symbols: /[=><!~?:&|+\-*/^%]+/,
  tokenizer: {
    root: [
      [/\/\/.*$/, 'comment'],
      [/"([^"\\]|\\.)*"/, 'string'],
      [/'([^'\\]|\\.)*'/, 'string'],
      [
        /[a-zA-Z_]\w*(?=\.)/,
        { cases: { '@namespaces': 'namespace', '@default': 'variable' } },
      ],
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            '@keywords': 'keyword',
            '@default': 'identifier',
          },
        },
      ],
      [/@\s*[a-zA-Z_]\w*/, 'annotation'],
      [/\d+\.\d+([eE][-+]?\d+)?/, 'number.float'],
      [/\d+/, 'number'],
      [/[{}()[\]]/, '@brackets'],
      [/@symbols/, 'operator'],
      [/[,:;]/, 'delimiter'],
    ],
  },
}
